---
- name: Provissioning Servers
  hosts: all
  become: yes
  tasks:
    - name: Install Chrony in Centos
      yum:
        name: chrony
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install NTP in Ubuntu
      apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Starting Chrony in Centos
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
   
    - name: Starting  NTP in Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"


