---
- name: DB setup
  hosts: dbservers
  become: yes
  vars: 
    dbname: rare
    dbusr: adhi
    dbpass: sekar 
  tasks:
    - debug:
         msg: The DB Name is "{{dbname}}"
    - debug:
        var: dbusr
    - name: Install Mariadb
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Install Python module
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start Service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database
      mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create database user 
      mysql_user:
        name: "{{dbusr}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      register: dbout

    - name: Printing Output
      debug:
        var: dbout
