---
galaxy_info:
  author: gano
  description: install java
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - xenial # 16.04
  galaxy_tags:
    - java

#dependencies: [ gano2018.ansible_os_init ]
